name: colorus
description: Colorus - Multiple easy to use Color Pickers with small footprint
version: 1.0.0
homepage: https://www.djarjo.com/colorus
issue_tracker: https://github.com/hlemcke/colorus/issues
repository: https://github.com/hlemcke/colorus
screenshots:
  - description: 'All Choosers'
    path: screenshots/all_choosers.png

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true